DROP TABLE IF EXISTS CURSOS;
DROP TABLE IF EXISTS PROFESORES;

CREATE TABLE PROFESORES (
       ID INT NOT NULL AUTO_INCREMENT
     , NOMBRE VARCHAR(100) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE CURSOS (
       ID INT NOT NULL AUTO_INCREMENT
     , PROFESOR_ID INT NOT NULL
     , TITULO VARCHAR(100) NOT NULL
     , NIVEL INT NOT NULL
     , HORAS INT NOT NULL
     , ACTIVO BOOLEAN NOT NULL
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_CURSOS_1 FOREIGN KEY (PROFESOR_ID) REFERENCES PROFESORES (ID)
);
